language: ruby

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10

before_install:
  - gem update --remote bundler
  - gem update --system

sudo: false

bundler_args: --without=guard

notifications:
  disabled: true
